on:
  schedule:
    - cron: '0 */4 * * *'
    
  workflow_dispatch:
  
name: Run-precipitation-scraper

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.TOKEN }}
      GSHEET_PRECIPITATION_PASSWORD: ${{ secrets.GSHEET_PRECIPITATION_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::rvest
            any::stringr            
            any::tidyr
            any::googlesheets4            
            any::lubridate
            any::remotes
            
      - name: install-tokencodr-package
        run: |
          echo 'remotes::install_github("jdtrat/tokencodr")' > install-packages.R
          Rscript install-packages.R
          
          
      - name: Cache R dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ env.R_LIBS_USER }}-{{ env.GITHUB_SHA }}
          restore-keys: |
            ${{ env.R_LIBS_USER }}-
        
      - name: Scrape
        run: |
          Rscript "precipitation-scraper.R"
